"""Build the committed geocode seed: data/geocode-seed.json.

Why this exists
---------------
`geocode()` caches in-process, which dies with the process. There is no
Fly volume, so nothing written at runtime survives a deploy either. The
only durable layer available is a file in the repo — this builds it.

The seed answers instantly, costs no outbound request, and keeps the
address chain working when NYC GeoSearch is down (measured 2026-07-29:
5 of 15 identical requests failed, and the API went fully dark twice in
~90 minutes).

Note this is NOT the "pre-warm the cache" anti-pattern CLAUDE.md warns
about. That failed because the old key was casefold-only, so warming one
spelling protected only that spelling. Entries here are stored under
`normalize_address_key()`, the same function `geocode()` looks up with,
so every spelling variant of a seeded address hits.

Usage
-----
    uv run python scripts/build_geocode_seed.py                 # default list
    uv run python scripts/build_geocode_seed.py addresses.txt   # one per line

Re-running rewrites the file; review the diff before committing. An
address that fails to resolve is reported and left OUT of the seed
entirely, so a bad build can't pin a permanent no-match.
"""
import asyncio
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app import config
from app.services import zoning
from app.services.zoning import geocode, normalize_address_key

# Addresses worth guaranteeing: the demo chain plus a spread of
# recognizable civic landmarks across all five boroughs, so a live
# walk-up gets an answer even during an upstream outage.
DEFAULT_ADDRESSES = [
    "428 W 26th St, Manhattan",          # the demo opener -> Chelsea Prep
    "180 7th Ave, Brooklyn",             # PS 321, the zoning fixture
    "20 W 44th St, Manhattan",
    "1 Bowling Green, Manhattan",
    "31 Chambers St, Manhattan",
    "455 5th Ave, Manhattan",
    "209 Joralemon St, Brooklyn",
    "1 Pierrepont Plaza, Brooklyn",
    "120-55 Queens Blvd, Queens",
    "89-14 Parsons Blvd, Queens",
    "851 Grand Concourse, Bronx",
    "2400 Halsey St, Bronx",
    "10 Richmond Terrace, Staten Island",
    "130 Stuyvesant Place, Staten Island",
]


async def build(addresses: list[str]) -> dict:
    entries: dict[str, dict] = {}
    failures: list[str] = []
    for addr in addresses:
        # Bypass the seed itself so a rebuild always re-resolves upstream.
        zoning.clear_geocode_cache()
        result = await geocode(addr)
        if result is None:
            failures.append(addr)
            print(f"  MISS  {addr}")
            continue
        key = normalize_address_key(addr)
        entries[key] = result.model_dump()
        print(f"  ok    {addr}  ->  {key}")
    if failures:
        print(f"\n{len(failures)} address(es) did not resolve and were omitted:")
        for addr in failures:
            print(f"  - {addr}")
    return {
        "_comment": (
            "Generated by scripts/build_geocode_seed.py. Keys are "
            "normalize_address_key() output, not raw addresses. Review the "
            "diff before committing."
        ),
        "entries": entries,
    }


def main() -> int:
    if len(sys.argv) > 1:
        source = Path(sys.argv[1])
        addresses = [ln.strip() for ln in source.read_text().splitlines() if ln.strip()]
    else:
        addresses = DEFAULT_ADDRESSES
    print(f"Resolving {len(addresses)} address(es) against NYC GeoSearch...\n")
    # An empty GEOCODE_SEED_PATH keeps a stale seed from short-circuiting
    # the rebuild via the in-process lookup order.
    import os
    os.environ["GEOCODE_SEED_PATH"] = "/nonexistent-seed-during-build.json"
    payload = asyncio.run(build(addresses))
    out = config.COMMITTED_DATA_DIR / "geocode-seed.json"
    out.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"\nWrote {len(payload['entries'])} entries to {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
